import os
import sys
# Add parent dir to path so we can import 'core'
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))
from core.providers import gemini_flash_lite, groq_llama3

TOPICS = [
    "AI Agents for Real Estate", 
    "Automated Email Marketing 2026", 
    "Python for SEO Automation",
    "Best Free AI APIs 2026"
]

def generate_seo_cluster():
    print("Starting Daily SEO Cluster Generation...")
    
    for topic in TOPICS:
        print(f"--> Processing Topic: {topic}")
        
        # 1. Strategy (Gemini - High IQ)
        strategy_prompt = f"Create a 5-point H2 outline for a high-ranking blog post about '{topic}' focusing on actionable python code."
        outline = gemini_flash_lite(strategy_prompt)
        
        # 2. Drafting (Groq - Speed)
        # We split the work to save Gemini rate limits for the hard stuff
        draft_prompt = f"Using this outline, write a full 1500 word article. Use strict Markdown.\n\nOutline:\n{outline}"
        full_article = groq_llama3(draft_prompt)
        
        # 3. Save
        filename = f"products/seo_pages/output/{topic.replace(' ', '_')}.md"
        os.makedirs(os.path.dirname(filename), exist_ok=True)
        
        with open(filename, "w") as f:
            f.write(f"# {topic}\n\n")
            f.write(f"*> Generated by Classic AI Pipeline*\n\n")
            f.write(full_article)
            
        print(f"    Saved: {filename}")

if __name__ == "__main__":
    generate_seo_cluster()
