import os
import sys
import time
import re

# Add parent dir to path so we can import 'core'
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))
sys.path.append(ROOT)

from core.providers import gemini_flash_lite, groq_llama3

TOPICS = [
    # -- Initial Batch --
    "AI Agents for Real Estate", 
    "Automated Email Marketing 2026", 
    "Python for SEO Automation",
    "Best Free AI APIs 2026",
    
    # -- New Batch (SEO & Automation) --
    "How to Build a Programmatic SEO Site with Next.js",
    "Top 10 Python Libraries for SEO Analysis",
    "Automating Keyword Research with Google Gemini",
    "Using Cloudflare Workers for SEO Redirects",
    "Next.js vs WordPress for SEO in 2026",
    "How to Generate SEO Meta Descriptions with AI",
    "Building an Internal Link Graph with Python",
    "Technical SEO Audit Checklist 2026",
    "Automating Google Search Console Reporting",
    "AI Content Strategy for B2B SaaS",
    
    # -- New Batch (AI Tools) --
    "Best Open Source LLMs for Content Generation",
    "How to Fine-Tune Llama 3 for SEO Writing",
    "Building an AI Writing Assistant with Groq",
    "Automating Social Media Posts with Pollinations AI",
    "Using AI Agents for Competitor Analysis",
    "How to Scale Content Production with Python",
    
    # -- New Batch (Niche Verticals) --
    "SEO Strategies for Real Estate Agents",
    "AI Marketing Automation for E-commerce",
    "Local SEO Automation for Small Business",
    "Programmatic SEO for Travel Websites",
    "Automating Lead Generation with AI Agents"
]


def slugify(text):
    """Convert title to SEO-friendly slug (e.g., 'AI Agents' -> 'ai-agents')"""
    text = text.lower()
    return re.sub(r'[^a-z0-9]+', '-', text).strip('-')

def generate_seo_cluster():
    print("Starting Daily SEO Cluster Generation...")
    
    # Define the output directory inside the Next.js app
    output_dir = os.path.join(ROOT, "web", "content", "posts")
    os.makedirs(output_dir, exist_ok=True)
    
    for topic in TOPICS:
        print(f"--> Processing Topic: {topic}")
        
        # 1. Strategy (Gemini - High IQ)
        strategy_prompt = f"Create a 5-point H2 outline for a high-ranking blog post about '{topic}' focusing on actionable python code."
        outline = gemini_flash_lite(strategy_prompt)
        
        # 2. Drafting (Groq - Speed)
        draft_prompt = f"Using this outline, write a full 1500 word article. Use strict Markdown. Do NOT include the Title at the top (it will be in frontmatter).\n\nOutline:\n{outline}"
        full_article = groq_llama3(draft_prompt)
        
        # 3. Save as MDX with Frontmatter
        slug = slugify(topic)
        filename = os.path.join(output_dir, f"{slug}.mdx")
        
        # Create today's date in YYYY-MM-DD format
        today = time.strftime('%Y-%m-%d')
        
        # Create a short excerpt (first 140 chars or generic)
        excerpt = f"Learn everything you need to know about {topic} in this comprehensive guide."
        
        file_content = f"""---
title: "{topic}"
date: "{today}"
excerpt: "{excerpt}"
---

*> Generated by Classic AI Pipeline*

{full_article}
"""
        
        with open(filename, "w", encoding="utf-8") as f:
            f.write(file_content)
            
        print(f"    Saved: {filename}")

if __name__ == "__main__":
    generate_seo_cluster()
